version: "3.8"

services:
  php-server:
    container_name: backend-php-server
    build:
      context: ./php-server
    ports:
      - "80:80"
    volumes:
      - ./php-server:/var/www/html

  db:
    container_name: backend-db
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  phpmyadmin:
    container_name: backend-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db

  cron:
    container_name: backend-cron
    build:
      context: ./cron
    volumes:
      - ./db-backup:/db-backup
      - ./cron/logs:/var/log/cron
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    depends_on:
      - db

volumes:
  db_data:
